"""Architecture-neutral preprocessing contracts: query layouts and targets."""

from gliner2.processing.layouts import (
    build_query_layout,
    SpanAnnotation,
    validate_target_graph,
)
from gliner2.processing.targets import (
    MentionTarget,
    ChoiceTarget,
    InstanceTarget,
    EdgeTarget,
    LiteralTarget,
    RecordFieldTarget,
    RecordTarget,
    TargetGraph,
    PaddedTargetBatch,
    TargetCapacityError,
    char_span_to_word_boundaries,
    inclusive_tokens_to_boundary_pair,
    word_boundaries_to_char_span,
    build_boundary_targets,
    pad_target_graphs,
    apply_truncation_policy,
    normalize_surface_occurrences,
)
from gliner2.processing.records import (
    FieldCardinality,
    RecordFieldSpec,
    RecordSpec,
    compile_record_specs,
    normalize_record_metadata,
)
__all__ = [
    "build_query_layout",
    "SpanAnnotation",
    "MentionTarget",
    "ChoiceTarget",
    "InstanceTarget",
    "EdgeTarget",
    "LiteralTarget",
    "RecordFieldTarget",
    "RecordTarget",
    "TargetGraph",
    "PaddedTargetBatch",
    "TargetCapacityError",
    "char_span_to_word_boundaries",
    "inclusive_tokens_to_boundary_pair",
    "word_boundaries_to_char_span",
    "build_boundary_targets",
    "pad_target_graphs",
    "apply_truncation_policy",
    "normalize_surface_occurrences",
    "FieldCardinality",
    "RecordFieldSpec",
    "RecordSpec",
    "compile_record_specs",
    "normalize_record_metadata",
    "validate_target_graph",
]
